version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mcp_gateway
      POSTGRES_USER: mcp_user
      POSTGRES_PASSWORD: mcp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcp_user -d mcp_gateway"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build: .
    environment:
      DATABASE_URL: postgresql://mcp_user:mcp_password@postgres:5432/mcp_gateway
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ENVIRONMENT: development
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./mcp_gateway:/app/mcp_gateway
    restart: unless-stopped

volumes:
  postgres_data: